defaults:

  - base_train
  - hydra/logging

  # Testing Models
  - model: unet_extensive
  # - model: transformer_extensive
  
  # Downloaded Models
  # - model_download/bumbling-sweep-23@model

  - wandb: train

  - _self_

###############
#    CONF     #
###############
cache_path: data/cache
debug: false
allow_multiple_instances: true

sweep_data:
  model_sizes:
    - [32, 64]
    - [64, 128]
    - [16, 32, 64]
    - [32, 64, 128]