defaults:
  - base_train
  - hydra/logging
  - wandb: train

  # Testing Models
  # - model: unet
  # - model: transformer
  - model: transformer_sparse
  
  # Downloaded Models
  # - model_download/bumbling-sweep-23@model    # Transformer - best param before bugfixes
  # - model_download/jolly-forest-1320@model    # Transformer - best param after bugfixes
  # - model_download/divine-sweep-43@model       # Transformer - agent only
  # - model_download/fearless-sweep-22@model     # U-Net - agent only

  # - model_download/dazzling-sweep-45@model      # Transformer - best with two_agent_penalty
  # - model_download/serene-sweep-11@model        # Transformer - best CombAction

  - _self_

###############
#    CONF     #
###############
# n_trials: 10
# trial_idx: null

cache_path: data/cache
debug: false
