enabled: True
project: Thesis
entity: a-ebersberger-tu-delft
job_type: train

log_config: True
log_code:
  enabled: True
  exclude: ^(.devenv/|venv.*/|.venv.*/|.vscode/|data/|notebooks/|outputs/|tests/|tm/|wandb/|manual.py|download_model.py)
