defaults:
  - pipeline/default@_here_
  - _self_

env_sys:
  steps:
    - _target_: src.modules.environment.gymnasium.GymnasiumBuilder
      environment: MiniGrid-Empty-5x5-v0

    - _target_: src.modules.environment.gymnasium.MinigridSamplerExtensive
      train_envs: 1
      validation_envs: 1

train_sys:
  steps:
    - _target_: src.modules.training.torch_trainer.TorchTrainer
      model_name: "U-Net"

      epochs: 5
      batch_size: 2048
      # patience: 10
      oversampling_factor: 100
      to_predict: "all"
      checkpointing_enabled: false

      model:
        _target_: src.modules.training.models.unet.UNet
        hidden_channels: [32, 64]

      optimizer:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.AdamW
        lr: 0.001

      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.step_lr.StepLRScheduler
        decay_t: 2
        decay_rate: 0.5

      dataloader_args:
        num_workers: 8
        prefetch_factor: 4
        persistent_workers: false

pred_sys:
  steps:
    - _target_: src.modules.scoring.minigrid_scorer.MinigridScorer