defaults:
  - pipeline/default@_here_
  - _self_

env_sys:
  steps:
    - _target_: src.modules.environment.gymnasium.GymnasiumBuilder
      # environment: MiniGrid-Empty-5x5-v0
      # environment: MiniGrid-Fetch-8x8-N3-v0
      environment: MiniGrid-LavaCrossingS9N3-v0
      # environment: MiniGrid-LavaCrossingS11N5-v0

    - _target_: src.modules.environment.gymnasium.MinigridSamplerExtensive
      train_envs: 5
      validation_envs: 1

train_sys:
  steps:
    - _target_: src.modules.training.torch_trainer.TorchTrainer

      epochs: 500
      batch_size: 2048
      # patience: 200

      load_all_batches_to_gpu: true
      validate_every_x_epochs: 5
      to_predict: ALL # NONE | TRAIN | VALIDATION | TEST | ALL
      discrete: true

      n_folds: ${n_trials}

      model:
        # _target_: src.modules.training.models.unet_wrapped.UNetWrapped
        _target_: src.modules.training.models.unet_wrapped_agent_only.UNetWrappedAgentOnly
        hidden_channels: [48, 96, 192, 384]

      loss:
        _target_: src.modules.training.loss.MinigridLoss
        obs_loss_weight: 0.8
        reward_loss_weight: 0.2
        # dynamic_var_weight: 1.0
        discrete_loss_fn:
          _target_: src.utils.functools.partial
          _args_:
            - _target_: hydra.utils.get_method
              # path: torch.nn.functional.cross_entropy
              # path: src.modules.training.loss.ce_focal_loss
              # path: src.modules.training.loss.ce_adaptive_loss
              path: src.modules.training.loss.ce_rebalance_loss

      accuracy:
        _target_: src.modules.training.accuracy.MinigridAccuracy

      model_storage_conf:
        save_model_to_disk: true
        save_model_to_wandb: true
        save_checkpoints_to_disk: false
        save_checkpoint_every_x_epochs: 1
        resume_training_from_checkpoint: false
        save_directory: !!python/object/apply:pathlib.PosixPath
          - 'tm/'

      dataloader_conf:
        num_workers: 8
        prefetch_factor: 4
        persistent_workers: true

      optimizer:
        _target_: src.utils.functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.AdamW
        lr: 0.001

      scheduler:
        _target_: src.utils.functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.step_lr.StepLRScheduler
        decay_t: 100
        decay_rate: 0.5

pred_sys:
  steps:
    - _target_: src.modules.scoring.minigrid_accuracy.MinigridAccuracy
      accuarcy_calc: ${model.train_sys.steps[0].accuracy}
    - _target_: src.modules.scoring.minigrid_heatmap.MinigridHeatmap
      metric_calculators: 
        # - AgentPovCertaintyCalc
        # - AgentPovAccuracyCalc
        - FieldPovAccuracyCalc
    # - _target_: src.modules.scoring.minigrid_sample_eval_text.MinigridSampleEvalText
    # - _target_: src.modules.scoring.minigrid_sample_eval_image.MinigridSampleEvalImage